[global]
checkNewVersion = true
sendAnonymousUsage = false

[entryPoints]
[entryPoints.web]
address = ":80"

[accessLog]
filePath = "/root/traefik/logs/access.log"
format = "common"

[log]
filePath = "/root/traefik/logs/traefik.log"
format = "json"

[api]
insecure = true
dashboard = true

[ping]

[providers.docker]
exposedByDefault = false
